### ISSUE TITLE
Update About page of the blog.

### ISSUE THREAD

**Issue by ravijainpro** [developerspoint-org/developerspoint.github.io#19]

**Comment by LowNightSnack** [comment]
Please look into #30

**Comment by ravijainpro** [comment]
-The [Developers Point](https://developerspoint.org) is a tech community run by student developers of [National Institute of Technology, Andhra Pradesh](https://www.nitandhra.ac.in) 
-The main characteristics that lay the foundation of what the Developers Point stands for are curiosity and a willingness to learn. 
-Moreover, the community consists of passionate developers from various streams & diverse skill sets (Android dev, Web dev, Machine Learning Enthusiasts,  Competitive coders, Graphic Designers, and the list goes on), the team collaboratively share ideas and work together to create a positive social impact. 
-Community organizes/conduct workshops, webinars, networking sessions, and everything possible to manifest our mission and vision. It also provides a platform for folks to collaborate, share ideas, get connected, and develop their knowledge in a peer-to-peer learning fashion.  
- Events are an integral aspect, apart from empowering folks to develop their skills the community also offers a platform for them to learn new skills. One with non-technical background gets the opportunity to smoothly venture into the tech field with tons of guidance and mentorship readily available to them. 
- The community is backed by various programs to name few: [Developer Student Club](), [Microsoft Student Partner](https://www.wikiwand.com/en/Microsoft_Student_Partners), [Mozilla](), [CodeChef](), [Explore ML](), the lists goes on..
- Club conducts regular online workshops, weekly blogging (primary focus is to train young minds), teach & learn sessions by resources & aid offered by Microsoft, Google, etc.

VISION
Developers Point as an open Source community strives to create a conscious tech eco-system.  

MISSION
- Empower the community for a social impact.

SOCIAL MEDIA PRESENCE 
(Just keep LinkedIn & GitHub icons (along with redirection link (use target='_blank'))

**Comment by ravijainpro** [comment]
@prilily create a final draft and post it over here.
I would request @AnjaniGss @AnAvid-ME @ShrishShukla  @subSri and the team to review it. 
We are open for changes and suggestions.

**Comment by prilily** [comment]
ABOUT
              
The Developers Point is a tech community run by student developers of National Institute of Technology, Andhra Pradesh. The main characteristics that lay the foundation of what the Developers Point stands for are curiosity and a willingness to learn. The community consists of passionate developers from various streams with diverse skill sets (Android Dev, Web Dev, Machine Learning Enthusiasts,  Competitive coders, Graphic Designers), the team collaboratively share ideas and work together to create a positive social impact. 

The community actively conducts workshops, webinars, networking sessions, and everything possible to manifest our mission and vision. It also provides a platform for folks to collaborate, share ideas,  connect and develop their knowledge in a peer-to-peer learning environment.

Events are an integral aspect, apart from empowering folks to develop their skills the community also offers a platform for them to learn new skills. Club conducts regular online workshops, weekly blogging (primary focus is to train young minds), teach & learn sessions by resources & aid offered by Microsoft, Google, etc.  Ones with non-technical background get the opportunity to smoothly venture into the tech field with tons of guidance and mentor ship readily available to them.

Developers Point is backed by various programs : Developer Students Club , Microsoft Student Partner,Mozilla Campus Clubs, CodeChef,Explore ML. With the aid of these programs and our diligent efforts we try to help our peers go from an idea to execution on a product/service thus making use of our learning and giving back to the community.

         
                                                  VISION
                                                                    
Developers Point as an open Source community strives to create a conscious tech Eco-system.  

                                                 MISSION
Empower the community for a social impact.



> @prilily create a final draft and post it over here.
> I would request @AnjaniGss @AnAvid-ME @ShrishShukla @subSri and the team to review it.
> We are open for changes and suggestions.

**Comment by ravijainpro** [comment]
@prilily we can go ahead with this.
