### ISSUE TITLE
Fetch assets from ripo (HTTPS Alert!)

### ISSUE THREAD

**Issue by ravijainpro** [developerspoint-org/developerspoint.github.io#20]
Author images or some external images used in blog must be fetched directly from the raw file i.e, from this repo, don't fetch them from some other source (Because this will make the HTTPS header unsecure, we shouldn't be fetching any data over HTTP). Kindly, upload them in **assets/img/uploads** folder (Review it and understand the structure) & update the path to images & author pic in blog and author pages.

**Comment by ravijainpro** [comment]
PFA for reference.
![Screenshot from 2020-11-17 12-45-11](https://user-images.githubusercontent.com/34270478/99357997-e8dd6a00-28d2-11eb-9852-0943fbf53d0d.png)

**Comment by ravijainpro** [comment]
Close the issue once fixed and follow this for further posts.

**Comment by Saicharan67** [comment]
Done from my side..

**Comment by ravijainpro** [comment]
> Done from my side..

Cool!

**Comment by LowNightSnack** [comment]
[Found something](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)
This is to be changed:
![image](https://user-images.githubusercontent.com/56243233/99501537-e3028a00-29a1-11eb-8e39-cb269d615b14.png)
from `http` to `https`.

**Comment by LowNightSnack** [comment]
@ketan-b please add cover image to [this](https://blog.developerspoint.org/Introduction-To-Scikit-learn/) blog.

**Comment by ketan-b** [comment]
> @ketan-b please add cover image to [this](https://blog.developerspoint.org/Introduction-To-Scikit-learn/) blog.

Already a Cover image is there, it is taking a little time to load, because of the Quality. 
I will look into it.

**Comment by ravijainpro** [comment]
> [Found something](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)
> This is to be changed:
> ![image](https://user-images.githubusercontent.com/56243233/99501537-e3028a00-29a1-11eb-8e39-cb269d615b14.png)
> from `http` to `https`.

Kindly use relative paths. 
Ed: **../assets/imgs/etc/etc**

**Comment by LowNightSnack** [comment]
Issue resolved.
