### ISSUE TITLE
Check & fix the labeler action!

### ISSUE THREAD

**Issue by ravijainpro** [developerspoint-org/developerspoint.github.io#27]
[Reference](https://github.com/actions/labeler/issues/16)

**Comment by LowNightSnack** [comment]
It is not a bug. More towards incomplete configuration. There is a configuration file missing, that is, `.github/labeler.yml`. 
This file maps labels to the commits in specific changes in directories.
Working on the file. Please do suggest what labels might be added.

**Comment by ravijainpro** [comment]
Alright. The below default labels would work:
1. **Bug** (Something isn't working)
2. **Dependencies** (Pull request that updates a dependency file)
3. **Documentation** (improved or additions to documentation)
4. **Duplicate** (This issue or pull request already exists)
5. **Enhancement** (New feature or request)
6. **Good First Issue** (Good for newcomers)
7. **Help wanted** (Extra attention is needed)
8. **Invalid** (This doesn't seem right)
9. **Question** (Further information is requested)
10. **Urgent** (Fix it asap!)

**Comment by LowNightSnack** [comment]
I think this won't be possible. [Reference](https://github.com/actions/labeler#pull-request-labeler)

**Comment by ravijainpro** [comment]
@chaithanyarlk kindly go through the reference shared above and share your views on it.

**Comment by chaithanyarlk** [comment]
Yeah @ravijainpro bhayya sure I will try.
