### ISSUE TITLE
CNAME Record (Hosting related)

### ISSUE THREAD

**Issue by ravijainpro** [developerspoint-org/developerspoint.github.io#29]
_The page build completed successfully, but returned the following warning for the `ravi` branch:_

_Your site's DNS settings are using a custom subdomain, blog.developerspoint.org, that's set up as an A record. We recommend you change this to a CNAME record pointing at developerspoint-org.github.io. For more information, see https://docs.github.com/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site._

_For information on troubleshooting Jekyll see:_

  _**https://docs.github.com/articles/troubleshooting-jekyll-builds**_

_If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=296924075&page_build_id=215658239_

**Anyone interested to take this just drop your azure ID in the comments, I'll give you access to the DNS record set.**

**Comment by ravijainpro** [comment]
@ksrikar1234 kindly look into this issue.

**Comment by ksrikar1234** [comment]
> @ksrikar1234 kindly look into this issue.

@ravijainpro  okay
