### ISSUE TITLE
Home page required?

### ISSUE THREAD

**Issue by LowNightSnack** [developerspoint-org/developerspoint.github.io#30]
Right now, our blog runs from the `blog` subdomain. I think it would be better if a home page is added to developerspoint.org which then links the blog. This would also remove `About` section from the `blog` subdomain.

**Comment by ravijainpro** [comment]
We are yet to design the wireframe. Will soon revert on it.

**Comment by ravijainpro** [comment]
**Update:** The team is of 13 (including me). Post end exams we will start with the website development.
