### ISSUE TITLE
Pull Request template required.

### ISSUE THREAD

**Issue by LowNightSnack** [developerspoint-org/developerspoint.github.io#32]
To submit a blog, a Pull Request template is required.
It might have two parts, one with a new post checklist, the other with a new-feature/bug-fix checklist.
The former is required because there are some rules to be followed while putting up a request for a new blog post.

**Comment by LowNightSnack** [comment]
Please comment the rules you feel should be added here

**Comment by LowNightSnack** [comment]
Few of the rules could be:
* The file should be of the format `YYYY-MM-DD-title-in-lowercase.md`
* There should be a cover image

**Comment by Saicharan67** [comment]
Author file to be added for new blogger in `author` folder

**Comment by ravijainpro** [comment]
All the assets must be fetched from the repo. [HTTPS Issue]

**Comment by ravijainpro** [comment]
@itsRkator can you take up this issue?

**Comment by itsRkator** [comment]
@ravijainpro I can fix this but need time as I have OS Minor tomorrow, labs in this week & few internship tests & interview.

**Comment by ravijainpro** [comment]
Fixed.
