### ISSUE TITLE
Is the logo inverted?

### ISSUE THREAD

**Issue by LowNightSnack** [developerspoint-org/developerspoint.github.io#33]
Is it me or the logo seems to look like it is inverted?

**Comment by Saicharan67** [comment]
Yeah it's inverted 😅

**Comment by ravijainpro** [comment]
@prilily kindly look into it.

**Comment by ravijainpro** [comment]
Good work @prilily .
Just update the below mentioned files in **assets/img/logos**
1. manifest.json
2. apple-touch-icon-114x114.png
3. apple-touch-icon-120x120.png
4. apple-touch-icon-144x144.png
5. apple-touch-icon-152x152.png
6. apple-touch-icon-57x57.png
7. apple-touch-icon-60x60.png
8. apple-touch-icon.png
9. browserconfig.xml

**Comment by ravijainpro** [comment]
Fixed
