### ISSUE TITLE
Drop "welcome" tag

### ISSUE THREAD

**Issue by ravijainpro** [developerspoint-org/developerspoint.github.io#40]
@Saicharan67 add a NumPy tag. Refer the image attached below. 
![Screenshot from 2020-11-23 10-31-08](https://user-images.githubusercontent.com/34270478/99930554-7b6c8600-2d77-11eb-82ff-6fa0a4bc499a.png)

**Comment by ravijainpro** [comment]
@developerspoint-org/numpy-sklearn-pandas I believe you should be dropping the welcome tag. Any opinion on it?

**Comment by Saicharan67** [comment]
Added numpy tags;
Dont know the use of it, but removed..

**Comment by ravijainpro** [comment]
> Dont know the use of it, but removed..

It's for SEO, relevant tags ensures audience can have better reach to the blog post.

**Comment by ravijainpro** [comment]
> @developerspoint-org/numpy-sklearn-pandas I believe you should be dropping the welcome tag. Any opinion on it?

@shantanu16101998 @ketan-b drop the welcome tag and close this issue.

**Comment by ketan-b** [comment]
Fixed
