### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by ravijainpro** [developerspoint-org/developerspoint.github.io#41]
@shantanu16101998 Have a look at below attachments, Kindly keep different pictures (Check out NumPy & Sklearn blog posts)
![Screenshot from 2020-11-23 10-38-15](https://user-images.githubusercontent.com/34270478/99930777-562c4780-2d78-11eb-8df4-3417a497c5dc.png)
![Screenshot from 2020-11-23 10-38-28](https://user-images.githubusercontent.com/34270478/99930779-575d7480-2d78-11eb-8581-a72fee66a6ef.png)

**Comment by shantanu16101998** [comment]
Ok

**Comment by shantanu16101998** [comment]
Done
