### ISSUE TITLE
Deployment unsuccessful

### ISSUE THREAD

**Issue by LowNightSnack** [developerspoint-org/developerspoint.github.io#5]
#4 merge has not pushed the repository to deployment yet.
@subSri could you check the Gemfile for the error?
Also could you see that repository is deployed in GitHub Pages section in the settings of the repo?
![navigation1](https://user-images.githubusercontent.com/56243233/93965289-64adb100-fd7f-11ea-8f69-5f02ff876ecf.png)
![navigation2](https://user-images.githubusercontent.com/56243233/93965296-6aa39200-fd7f-11ea-9190-ff8ac39293f1.png)

**Comment by subSri** [comment]
The repository has been deployed

**Comment by LowNightSnack** [comment]
![image](https://user-images.githubusercontent.com/56243233/94110125-c34a5c00-fe5f-11ea-850a-c4a255e38885.png)

**Comment by LowNightSnack** [comment]
Deployment is still unsuccessful

**Comment by subSri** [comment]
Its blog.developerspoint.org
